/**
 * How `docs/flow-rules.md` is rendered from the lint registry.
 *
 * Kept apart from the generator so it can be imported without booting Vite —
 * the drift test needs the same function the script uses, or checking for drift
 * would just compare a copy against a copy.
 */

export function renderRulesDoc(rules) {
  const rows = (tier) => rules
    .filter((r) => r.severity === tier)
    .map((r) => `| \`${r.id}\` | ${r.requires} | ${r.because} |`)
    .join('\n')

  return `<!-- Generated by scripts/generate-rules-doc.mjs from src/engine/geometryLint.ts.
     Do not edit by hand: change the rule in the code and re-run the script. -->

# Flow layout rules

The rules a flow has to obey to *look* right, as opposed to the schema, which
decides whether it loads at all. Every one is checked by \`pnpm validate --lint\`
and shown live in edit mode.

They are measured against the geometry the renderer actually uses — the same
world-space boxes and baked curves it draws — so a finding predicts a visible
problem rather than approximating one.

## Errors

Mistakes rather than judgement calls. Nothing on disk trips these.

| Rule | Requires | Why |
|---|---|---|
${rows('error')}

## Warnings

Worth looking at, not worth blocking on. A hand-tuned layout may trade one away
deliberately — \`monopoly.json\` is a Monopoly board and has no room for zone
padding — so these never gate a save or fail a build unless you pass \`--strict\`.

| Rule | Requires | Why |
|---|---|---|
${rows('warning')}

## Checking a flow

\`\`\`bash
pnpm validate --lint             # every flow, findings printed, exit 0
pnpm validate --lint --strict    # findings fail the run too
\`\`\`

**Tidy layout** in edit mode (or \`pnpm validate --tidy <file>\`) re-lays a scene
to satisfy these rules: layered left to right, rows banded by zone, then
compacted as far as the rules allow. It is opt-in and one undo, because a
hand-tuned layout will generally come back larger than it went in.

In the app, turn on **Edit layout** and the findings appear as *layout notes* in
the sidebar. They never disable **Save to file**: a flow with bad geometry still
loads, and every drag passes through a bad state on the way to a good one.
`
}
